### ISSUE TITLE
Deploy Obsrv in OCI Cloud with Ease using One-Click Installation Terraform Script

### ISSUE THREAD

**Issue by manjudr** [Sunbird-Obsrv/obsrv-core#4]
# Project Details

## What is Sunbird Obsrv?

Sunbird Obsrv comprises several pluggable tools and microservices that come together to enable observability features on any platform/solution. This includes the ability to capture granular events via telemetry, create measures, and observe various events/actions carried out by the system/users/devices (like IoT devices) on any platform/solution. 

Sunbird Obsrv can be utilized as an independent building block by adopters or as part of a system that employs other Sunbird building blocks. Sunbird Obsrv comes with a set of microservices, APIs, and some utility SDKs to make it easy for adopters to rapidly enable powerful data processing and aggregation infrastructure to process telemetry data, validate telemetry stream data, as well as aggregate and generate actionable insights via APIs. It also has built-in open data cataloguing and publishing capability. It is built keeping extensibility in mind so that adopters have the flexibility to adapt the telemetry and tools to their specific use cases.
More details are [here](https://obsrv.sunbird.org/)

## Features to be implemented
 **One-click installation of Obsrv in OCI environment**

- Current Scenario:  Currently, one-click installation of Obsrv is enabled in Azure & AWS environment using terraforms.
- Acceptance Criteria: Enhance Obsrv one-click installation scripts to support the OCI environment

## Learning Path
- Complexity - Medium
- Skills Required - Terraform, Kubernetes, Docker, Helm
- Name of Mentors - @manjudr @anandp504 
- Project size - 8 Weeks

## Product Set Up

- Scripts - https://github.com/Sunbird-Obsrv/obsrv-automation/blob/main/README.md
- API Documentation - https://github.com/Sanketika-Obsrv/obsrv-api-service/tree/main/swagger-doc
- More details about the sunbird-obsrv - - https://obsrv.sunbird.org/use/installation-guide

## Milestones

- [ ]  Understand Obsrv one-click installation scripts
- [ ]  Enhance the terraform script to provision all the services (Kubernetes cluster, Druid, Secor, Postgres, Redis, Kafka ) 
- [ ]  Enhance scripts to deploy Obsrv Ingestion Service in OCI environments
- [ ]  Enhance scripts to deploy Obsrv Query Service in OCI environments
- [ ]  Enhance scripts to deploy Obsrv Processing Service in OCI environments

**Comment by wasup-yash** [comment]
hey @manjudr , I am interested to work on this project as I have some experience with Kubernetes and Docker.

**Comment by SuperAayush** [comment]
Hey @manjudr!!

Just went through the issue and looking forward to submitting a proposal for the project.

Thank You!!

**Comment by Aarav238** [comment]
Hey @manjudr  , I am computer Science under grad . I am familiar with full stack Development(MERN), I also have knowledge of containerization and I also hands on experience with postman . I would love to contribute in this project and explore more in the community. Can you please guide me how to get started?
